# Generated by Django 5.1.7 on 2025-03-27 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_useraccount_ref_code_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Date_Joined',
            field=models.DateField(default=datetime.datetime(2025, 3, 27, 9, 0, 35, 582339, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='Ref_Code',
            field=models.CharField(default='FHKCMN', max_length=6),
        ),
    ]
