# Generated by Django 5.1.7 on 2025-03-27 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_useraccount_is_revardclaimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Date_Joined',
            field=models.DateField(default=datetime.datetime(2025, 3, 27, 9, 22, 41, 188051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='Ref_Code',
            field=models.CharField(default='UNEKHS', max_length=6),
        ),
    ]
